---
- id: ossindex:pypi:Django:2017-04-04
  title: '[CVE-2017-7234]  URL Redirection to Untrusted Site ("Open Redirect")'
  description: A maliciously crafted URL to a Django (1.10 before 1.10.7, 1.9 before
    1.9.13, and 1.8 before 1.8.18) site using the ``django.views.static.serve()``
    view could redirect to any other domain, aka an open redirect vulnerability.
  affected_package: Django
  vulnerable_versions:
  - 1.9.7
  - 1.10.3
  - 1.8.12
  - 1.8.4
  - 1.9.10
  - 1.9.8
  - 1.10.4
  - 1.8.13
  - 1.8.5
  - 1.9.11
  - 1.9.9
  - 1.10.5
  - 1.8.14
  - 1.8.6
  - 1.9.12
  - 1.10.6
  - 1.8.15
  - 1.8.7
  - 1.9.2
  - 1.8.0
  - 1.8.16
  - 1.8.8
  - 1.9.3
  - 1.10.0
  - 1.8.1
  - 1.8.17
  - 1.8.9
  - 1.9.4
  - 1.10.1
  - 1.8.10
  - 1.8.2
  - '1.9'
  - 1.9.5
  - 1.10.2
  - 1.8.11
  - 1.8.3
  - 1.9.1
  - 1.9.6
  package_manager: pypi
  cve:
  - CVE-2017-7234
  credit:
  - OSSIndex
  references:
  - http://www.debian.org/security/2017/dsa-3835
  - http://www.securityfocus.com/bid/97401
  - http://www.securitytracker.com/id/1038177
  - https://www.djangoproject.com/weblog/2017/apr/04/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2017-04-04
  title: '[CVE-2017-7233]  URL Redirection to Untrusted Site ("Open Redirect")'
  description: Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18
    relies on user input in some cases to redirect the user to an "on success" URL.
    The security check for these redirects (namely ``django.utils.http.is_safe_url()``)
    considered some numeric URLs "safe" when they shouldn't be, aka an open redirect
    vulnerability. Also, if a developer relies on ``is_safe_url()`` to provide safe
    redirect targets and puts such a URL into a link, they could suffer from an XSS
    attack.
  affected_package: Django
  vulnerable_versions:
  - 1.10.1
  - 1.8.10
  - 1.8.2
  - '1.9'
  - 1.9.5
  - 1.10.2
  - 1.8.11
  - 1.8.3
  - 1.9.1
  - 1.9.6
  - 1.10.3
  - 1.8.12
  - 1.8.4
  - 1.9.10
  - 1.9.7
  - 1.10.4
  - 1.8.13
  - 1.8.5
  - 1.9.11
  - 1.9.8
  - 1.10.5
  - 1.8.14
  - 1.8.6
  - 1.9.12
  - 1.9.9
  - 1.10.6
  - 1.8.15
  - 1.8.7
  - 1.9.2
  - 1.8.0
  - 1.8.16
  - 1.8.8
  - 1.9.3
  - 1.10.0
  - 1.8.1
  - 1.8.17
  - 1.8.9
  - 1.9.4
  package_manager: pypi
  cve:
  - CVE-2017-7233
  credit:
  - OSSIndex
  references:
  - http://www.debian.org/security/2017/dsa-3835
  - http://www.securityfocus.com/bid/97406
  - http://www.securitytracker.com/id/1038177
  - https://access.redhat.com/errata/RHSA-2017:1445
  - https://access.redhat.com/errata/RHSA-2017:1451
  - https://access.redhat.com/errata/RHSA-2017:1462
  - https://access.redhat.com/errata/RHSA-2017:1470
  - https://access.redhat.com/errata/RHSA-2017:1596
  - https://access.redhat.com/errata/RHSA-2017:3093
  - https://www.djangoproject.com/weblog/2017/apr/04/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2014-05-16
  title: "[CVE-2014-3730]  Improper Input Validation"
  description: The django.util.http.is_safe_url function in Django 1.4 before 1.4.13,
    1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate
    URLs, which allows remote attackers to conduct open redirect attacks via a malformed
    URL, as demonstrated by "http:\\\djangoproject.com."
  affected_package: Django
  vulnerable_versions:
  - 1.4.10
  - 1.4.8
  - 1.5.6
  - 1.4.11
  - 1.4.9
  - 1.5.7
  - 1.4.12
  - '1.5'
  - '1.6'
  - 1.4.2
  - 1.5.1
  - 1.6.1
  - 1.4.4
  - 1.5.2
  - 1.6.2
  - 1.4.5
  - 1.5.3
  - 1.6.3
  - '1.4'
  - 1.4.6
  - 1.5.4
  - 1.6.4
  - 1.4.1
  - 1.4.7
  - 1.5.5
  - '1.7'
  package_manager: pypi
  cve:
  - CVE-2014-3730
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
  - http://secunia.com/advisories/61281
  - http://ubuntu.com/usn/usn-2212-1
  - http://www.debian.org/security/2014/dsa-2934
  - http://www.openwall.com/lists/oss-security/2014/05/14/10
  - http://www.openwall.com/lists/oss-security/2014/05/15/3
  - http://www.securityfocus.com/bid/67410
  - https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2014-05-16
  title: "[CVE-2014-1418] Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5,
    and 1.7 before 1.7..."
  description: 'Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and
    1.7 before 1.7b4 does not properly include the (1) Vary: Cookie or (2) Cache-Control
    header in responses, which allows remote attackers to obtain sensitive information
    or poison the cache via a request from certain browsers.'
  affected_package: Django
  vulnerable_versions:
  - 1.4.5
  - 1.5.3
  - 1.6.3
  - '1.4'
  - 1.4.6
  - 1.5.4
  - 1.6.4
  - 1.4.1
  - 1.4.7
  - 1.5.5
  - '1.7'
  - 1.4.10
  - 1.4.8
  - 1.5.6
  - 1.4.11
  - 1.4.9
  - 1.5.7
  - 1.4.12
  - '1.5'
  - '1.6'
  - 1.4.2
  - 1.5.1
  - 1.6.1
  - 1.4.4
  - 1.5.2
  - 1.6.2
  package_manager: pypi
  cve:
  - CVE-2014-1418
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
  - http://secunia.com/advisories/61281
  - http://ubuntu.com/usn/usn-2212-1
  - http://www.debian.org/security/2014/dsa-2934
  - http://www.openwall.com/lists/oss-security/2014/05/14/10
  - http://www.openwall.com/lists/oss-security/2014/05/15/3
  - https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2014-08-26
  title: "[CVE-2014-0483]  Permissions, Privileges, and Access Controls"
  description: The administrative interface (contrib.admin) in Django before 1.4.14,
    1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does
    not check if a field represents a relationship between models, which allows remote
    authenticated users to obtain sensitive information via a to_field parameter in
    a popup action to an admin change form page, as demonstrated by a /admin/auth/user/?pop=1&t=password
    URI.
  affected_package: Django
  vulnerable_versions:
  - 1.4.2
  - 1.5.1
  - '1.6'
  - 1.4.4
  - 1.5.2
  - 1.6.1
  - '1.4'
  - 1.4.5
  - 1.5.3
  - 1.6.2
  - 1.4.1
  - 1.4.6
  - 1.5.4
  - 1.6.3
  - 1.4.10
  - 1.4.7
  - 1.5.5
  - 1.6.4
  - 1.4.11
  - 1.4.8
  - 1.5.6
  - 1.6.5
  - 1.4.12
  - 1.4.9
  - 1.5.7
  - '1.7'
  - 1.4.13
  - '1.5'
  - 1.5.8
  package_manager: pypi
  cve:
  - CVE-2014-0483
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
  - http://secunia.com/advisories/59782
  - http://secunia.com/advisories/61276
  - http://secunia.com/advisories/61281
  - http://www.debian.org/security/2014/dsa-3010
  - https://github.com/django/django/commit/2b31342cdf14fc20e07c43d258f1e7334ad664a6
  - https://www.djangoproject.com/weblog/2014/aug/20/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2014-08-26
  title: "[CVE-2014-0482]  Improper Authentication"
  description: The contrib.auth.middleware.RemoteUserMiddleware middleware in Django
    before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release
    candidate 3, when using the contrib.auth.backends.RemoteUserBackend backend, allows
    remote authenticated users to hijack web sessions via vectors related to the REMOTE_USER
    header.
  affected_package: Django
  vulnerable_versions:
  - 1.4.11
  - 1.4.8
  - 1.5.6
  - 1.6.5
  - 1.4.12
  - 1.4.9
  - 1.5.7
  - '1.7'
  - 1.4.13
  - '1.5'
  - 1.5.8
  - 1.4.2
  - 1.5.1
  - '1.6'
  - 1.4.4
  - 1.5.2
  - 1.6.1
  - '1.4'
  - 1.4.5
  - 1.5.3
  - 1.6.2
  - 1.4.1
  - 1.4.6
  - 1.5.4
  - 1.6.3
  - 1.4.10
  - 1.4.7
  - 1.5.5
  - 1.6.4
  package_manager: pypi
  cve:
  - CVE-2014-0482
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
  - http://secunia.com/advisories/59782
  - http://secunia.com/advisories/61276
  - http://secunia.com/advisories/61281
  - http://www.debian.org/security/2014/dsa-3010
  - https://www.djangoproject.com/weblog/2014/aug/20/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2014-08-26
  title: "[CVE-2014-0481]  Resource Management Errors"
  description: The default configuration for the file upload handling system in Django
    before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release
    candidate 3 uses a sequential file name generation process when a file with a
    conflicting name is uploaded, which allows remote attackers to cause a denial
    of service (CPU consumption) by unloading a multiple files with the same name.
  affected_package: Django
  vulnerable_versions:
  - 1.4.5
  - 1.5.3
  - 1.6.2
  - '1.4'
  - 1.4.6
  - 1.5.4
  - 1.6.3
  - 1.4.1
  - 1.4.7
  - 1.5.5
  - 1.6.4
  - 1.4.10
  - 1.4.8
  - 1.5.6
  - 1.6.5
  - 1.4.11
  - 1.4.9
  - 1.5.7
  - '1.7'
  - 1.4.12
  - '1.5'
  - 1.5.8
  - 1.4.13
  - 1.5.1
  - '1.6'
  - 1.4.2
  - 1.5.2
  - 1.6.1
  - 1.4.4
  package_manager: pypi
  cve:
  - CVE-2014-0481
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
  - http://secunia.com/advisories/59782
  - http://secunia.com/advisories/61276
  - http://secunia.com/advisories/61281
  - http://www.debian.org/security/2014/dsa-3010
  - https://www.djangoproject.com/weblog/2014/aug/20/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2014-08-26
  title: "[CVE-2014-0480]  Improper Input Validation"
  description: The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x
    before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not
    properly validate URLs, which allows remote attackers to conduct phishing attacks
    via a // (slash slash) in a URL, which triggers a scheme-relative URL to be generated.
  affected_package: Django
  vulnerable_versions:
  - 1.4.10
  - 1.4.7
  - 1.5.5
  - 1.5.8
  - 1.4.11
  - 1.4.8
  - 1.5.6
  - '1.6'
  - 1.4.12
  - 1.4.9
  - 1.5.7
  - 1.6.1
  - 1.4.13
  - '1.5'
  - 1.6.2
  - 1.4.2
  - 1.5.1
  - 1.6.3
  - 1.4.4
  - 1.5.2
  - 1.6.4
  - '1.4'
  - 1.4.5
  - 1.5.3
  - 1.6.5
  - 1.4.1
  - 1.4.6
  - 1.5.4
  - '1.7'
  package_manager: pypi
  cve:
  - CVE-2014-0480
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
  - http://secunia.com/advisories/59782
  - http://secunia.com/advisories/61276
  - http://secunia.com/advisories/61281
  - http://www.debian.org/security/2014/dsa-3010
  - http://www.securityfocus.com/bid/69425
  - https://www.djangoproject.com/weblog/2014/aug/20/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2014-04-23
  title: "[CVE-2014-0474]  Resource Management Errors"
  description: The (1) FilePathField, (2) GenericIPAddressField, and (3) IPAddressField
    model field classes in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before
    1.6.3, and 1.7.x before 1.7 beta 2 do not properly perform type conversion, which
    allows remote attackers to have unspecified impact and vectors, related to "MySQL
    typecasting."
  affected_package: Django
  vulnerable_versions:
  - 1.4.6
  - 1.5.4
  - '1.4'
  - 1.4.7
  - 1.5.5
  - 1.4.1
  - 1.4.8
  - '1.6'
  - 1.4.10
  - 1.4.9
  - 1.6.1
  - 1.4.2
  - '1.5'
  - 1.6.2
  - 1.4.3
  - 1.5.1
  - '1.7'
  - 1.4.4
  - 1.5.2
  - 1.4.5
  - 1.5.3
  package_manager: pypi
  cve:
  - CVE-2014-0474
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
  - http://rhn.redhat.com/errata/RHSA-2014-0456.html
  - http://rhn.redhat.com/errata/RHSA-2014-0457.html
  - http://secunia.com/advisories/61281
  - http://www.debian.org/security/2014/dsa-2934
  - http://www.ubuntu.com/usn/USN-2169-1
  - https://www.djangoproject.com/weblog/2014/apr/21/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2014-04-23
  title: "[CVE-2014-0473]  Permissions, Privileges, and Access Controls"
  description: The caching framework in Django before 1.4.11, 1.5.x before 1.5.6,
    1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 reuses a cached CSRF token for
    all anonymous users, which allows remote attackers to bypass CSRF protections
    by reading the CSRF cookie for anonymous users.
  affected_package: Django
  vulnerable_versions:
  - 1.4.3
  - 1.5.1
  - '1.7'
  - 1.4.4
  - 1.5.2
  - 1.4.5
  - 1.5.3
  - 1.4.6
  - 1.5.4
  - 1.4.7
  - 1.5.5
  - '1.4'
  - 1.4.8
  - '1.6'
  - 1.4.1
  - 1.4.10
  - 1.4.9
  - 1.6.1
  - 1.4.2
  - '1.5'
  - 1.6.2
  package_manager: pypi
  cve:
  - CVE-2014-0473
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
  - http://rhn.redhat.com/errata/RHSA-2014-0456.html
  - http://rhn.redhat.com/errata/RHSA-2014-0457.html
  - http://secunia.com/advisories/61281
  - http://www.debian.org/security/2014/dsa-2934
  - http://www.ubuntu.com/usn/USN-2169-1
  - https://www.djangoproject.com/weblog/2014/apr/21/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2014-04-23
  title: '[CVE-2014-0472]  Improper Control of Generation of Code ("Code Injection")'
  description: The django.core.urlresolvers.reverse function in Django before 1.4.11,
    1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote
    attackers to import and execute arbitrary Python modules by leveraging a view
    that constructs URLs using user input and a "dotted Python path."
  affected_package: Django
  vulnerable_versions:
  - 1.4.1
  - 1.4.8
  - '1.6'
  - 1.4.10
  - 1.4.9
  - 1.6.1
  - 1.4.2
  - '1.5'
  - 1.6.2
  - 1.4.3
  - 1.5.1
  - '1.7'
  - 1.4.4
  - 1.5.2
  - 1.4.5
  - 1.5.3
  - 1.4.6
  - 1.5.4
  - '1.4'
  - 1.4.7
  - 1.5.5
  package_manager: pypi
  cve:
  - CVE-2014-0472
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
  - http://rhn.redhat.com/errata/RHSA-2014-0456.html
  - http://rhn.redhat.com/errata/RHSA-2014-0457.html
  - http://secunia.com/advisories/61281
  - http://www.debian.org/security/2014/dsa-2934
  - http://www.ubuntu.com/usn/USN-2169-1
  - https://www.djangoproject.com/weblog/2014/apr/21/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-08-24
  title: "[CVE-2015-5964]  Resource Management Errors"
  description: The (1) contrib.sessions.backends.base.SessionBase.flush and (2) cache_db.SessionStore.flush
    functions in Django 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other
    versions create empty sessions in certain circumstances, which allows remote attackers
    to cause a denial of service (session store consumption) via unspecified vectors.
  affected_package: Django
  vulnerable_versions:
  - 1.4.11
  - 1.4.21
  - 1.7.1
  - 1.7.9
  - 1.4.12
  - 1.4.4
  - 1.7.2
  - '1.8'
  - 1.4.13
  - 1.4.5
  - 1.7.3
  - 1.8.0
  - 1.4.14
  - 1.4.6
  - 1.7.4
  - 1.8.1
  - 1.8.2
  - 1.4.17
  - 1.4.7
  - 1.7.5
  - 1.8.3
  - '1.4'
  - 1.4.19
  - 1.4.8
  - 1.7.6
  - 1.4.1
  - 1.4.2
  - 1.4.9
  - 1.7.7
  - 1.4.10
  - 1.4.20
  - '1.7'
  - 1.7.8
  package_manager: pypi
  cve:
  - CVE-2015-5964
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html
  - http://rhn.redhat.com/errata/RHSA-2015-1766.html
  - http://rhn.redhat.com/errata/RHSA-2015-1767.html
  - http://rhn.redhat.com/errata/RHSA-2015-1894.html
  - http://www.debian.org/security/2015/dsa-3338
  - http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html
  - http://www.securityfocus.com/bid/76440
  - http://www.securitytracker.com/id/1033318
  - http://www.ubuntu.com/usn/USN-2720-1
  - https://www.djangoproject.com/weblog/2015/aug/18/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-08-24
  title: "[CVE-2015-5963]  Resource Management Errors"
  description: contrib.sessions.middleware.SessionMiddleware in Django 1.8.x before
    1.8.4, 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions allows
    remote attackers to cause a denial of service (session store consumption or session
    record removal) via a large number of requests to contrib.auth.views.logout, which
    triggers the creation of an empty session record.
  affected_package: Django
  vulnerable_versions:
  - 1.4.12
  - 1.4.4
  - 1.7.2
  - '1.8'
  - 1.4.13
  - 1.4.5
  - 1.7.3
  - 1.8.0
  - 1.4.14
  - 1.4.6
  - 1.7.4
  - 1.8.1
  - 1.4.17
  - 1.4.7
  - 1.7.5
  - 1.8.2
  - '1.4'
  - 1.4.19
  - 1.4.8
  - 1.7.6
  - 1.8.3
  - 1.4.1
  - 1.4.2
  - 1.4.9
  - 1.7.7
  - 1.4.10
  - 1.4.20
  - '1.7'
  - 1.7.8
  - 1.4.11
  - 1.4.21
  - 1.7.1
  - 1.7.9
  package_manager: pypi
  cve:
  - CVE-2015-5963
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html
  - http://lists.opensuse.org/opensuse-updates/2015-09/msg00026.html
  - http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html
  - http://rhn.redhat.com/errata/RHSA-2015-1766.html
  - http://rhn.redhat.com/errata/RHSA-2015-1767.html
  - http://rhn.redhat.com/errata/RHSA-2015-1894.html
  - http://www.debian.org/security/2015/dsa-3338
  - http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html
  - http://www.securityfocus.com/bid/76428
  - http://www.securitytracker.com/id/1033318
  - http://www.ubuntu.com/usn/USN-2720-1
  - https://access.redhat.com/errata/RHSA-2015:1876
  - https://www.djangoproject.com/weblog/2015/aug/18/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-07-14
  title: "[CVE-2015-5144]  Improper Input Validation"
  description: Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and
    1.8.x before 1.8.3 uses an incorrect regular expression, which allows remote attackers
    to inject arbitrary headers and conduct HTTP response splitting attacks via a
    newline character in an (1) email message to the EmailValidator, a (2) URL to
    the URLValidator, or unspecified vectors to the (3) validate_ipv4_address or (4)
    validate_slug validator.
  affected_package: Django
  vulnerable_versions:
  - '1.8'
  - 1.5.10
  - 1.5.7
  - 1.6.4
  - 1.7.2
  - 1.8.0
  - 1.5.11
  - 1.5.8
  - 1.6.5
  - 1.7.3
  - 1.7.4
  - 1.8.1
  - 1.5.12
  - 1.5.9
  - 1.6.6
  - 1.7.5
  - 1.8.2
  - 1.5.2
  - '1.6'
  - 1.6.7
  - 1.7.6
  - 1.5.3
  - 1.6.1
  - 1.6.8
  - 1.7.7
  - 1.4.20
  - 1.5.4
  - 1.6.10
  - 1.6.9
  - 1.7.8
  - '1.5'
  - 1.5.5
  - 1.6.2
  - '1.7'
  - 1.7.9
  - 1.5.1
  - 1.5.6
  - 1.6.3
  - 1.7.1
  package_manager: pypi
  cve:
  - CVE-2015-5144
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html
  - http://lists.opensuse.org/opensuse-updates/2015-10/msg00043.html
  - http://lists.opensuse.org/opensuse-updates/2015-10/msg00046.html
  - http://www.debian.org/security/2015/dsa-3305
  - http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html
  - http://www.securityfocus.com/bid/75665
  - http://www.securitytracker.com/id/1032820
  - http://www.ubuntu.com/usn/USN-2671-1
  - https://security.gentoo.org/glsa/201510-06
  - https://www.djangoproject.com/weblog/2015/jul/08/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-07-14
  title: "[CVE-2015-5143]  Resource Management Errors"
  description: The session backends in Django before 1.4.21, 1.5.x through 1.6.x,
    1.7.x before 1.7.9, and 1.8.x before 1.8.3 allows remote attackers to cause a
    denial of service (session store consumption) via multiple requests with unique
    session keys.
  affected_package: Django
  vulnerable_versions:
  - '1.5'
  - 1.5.5
  - 1.6.2
  - '1.7'
  - 1.7.8
  - 1.5.1
  - 1.5.6
  - 1.6.3
  - 1.7.1
  - 1.7.9
  - 1.5.10
  - 1.5.7
  - 1.6.4
  - 1.7.2
  - 1.8.0
  - 1.5.11
  - 1.5.8
  - 1.6.5
  - 1.7.3
  - 1.8.1
  - 1.5.12
  - 1.5.9
  - 1.6.6
  - 1.7.4
  - 1.8.2
  - 1.5.2
  - '1.6'
  - 1.6.7
  - 1.7.5
  - 1.5.3
  - 1.6.1
  - 1.6.8
  - 1.7.6
  - 1.4.20
  - 1.5.4
  - 1.6.10
  - 1.6.9
  - 1.7.7
  package_manager: pypi
  cve:
  - CVE-2015-5143
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html
  - http://lists.opensuse.org/opensuse-updates/2015-10/msg00043.html
  - http://lists.opensuse.org/opensuse-updates/2015-10/msg00046.html
  - http://rhn.redhat.com/errata/RHSA-2015-1678.html
  - http://rhn.redhat.com/errata/RHSA-2015-1686.html
  - http://www.debian.org/security/2015/dsa-3305
  - http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html
  - http://www.securityfocus.com/bid/75666
  - http://www.securitytracker.com/id/1032820
  - http://www.ubuntu.com/usn/USN-2671-1
  - https://security.gentoo.org/glsa/201510-06
  - https://www.djangoproject.com/weblog/2015/jul/08/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-03-25
  title: '[CVE-2015-2317]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: 'The utils.http.is_safe_url function in Django before 1.4.20, 1.5.x,
    1.6.x before 1.6.11, 1.7.x before 1.7.7, and 1.8.x before 1.8c1 does not properly
    validate URLs, which allows remote attackers to conduct cross-site scripting (XSS)
    attacks via a control character in a URL, as demonstrated by a \x08javascript:
    URL.'
  affected_package: Django
  vulnerable_versions:
  - 1.7.1
  - 1.5.3
  - 1.5.6
  - 1.6.3
  - 1.7.2
  - 1.4.19
  - 1.5.4
  - 1.5.7
  - 1.6.4
  - 1.7.3
  - '1.5'
  - 1.5.5
  - 1.5.8
  - 1.6.5
  - 1.7.4
  - 1.5.1
  - 1.5.9
  - 1.6.6
  - 1.7.5
  - 1.5.10
  - '1.6'
  - 1.6.7
  - 1.7.6
  - 1.5.11
  - 1.6.1
  - 1.6.8
  - 1.8.0
  - 1.5.12
  - 1.6.10
  - 1.6.9
  - 1.5.2
  - 1.6.2
  - '1.7'
  package_manager: pypi
  cve:
  - CVE-2015-2317
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-April/155421.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-June/160263.html
  - http://lists.opensuse.org/opensuse-updates/2015-04/msg00001.html
  - http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html
  - http://ubuntu.com/usn/usn-2539-1
  - http://www.debian.org/security/2015/dsa-3204
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:195
  - http://www.oracle.com/technetwork/topics/security/bulletinapr2015-2511959.html
  - http://www.securityfocus.com/bid/73319
  - https://www.djangoproject.com/weblog/2015/mar/18/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-01-16
  title: "[CVE-2015-0222]  Code"
  description: ModelMultipleChoiceField in Django 1.6.x before 1.6.10 and 1.7.x before
    1.7.3, when show_hidden_initial is set to True, allows remote attackers to cause
    a denial of service by submitting duplicate values, which triggers a large number
    of SQL queries.
  affected_package: Django
  vulnerable_versions:
  - 1.6.1
  - 1.6.9
  - 1.6.2
  - '1.7'
  - 1.6.3
  - 1.7.1
  - 1.6.4
  - 1.7.2
  - 1.6.5
  - 1.6.6
  - 1.4.17
  - 1.6.7
  - '1.6'
  - 1.6.8
  package_manager: pypi
  cve:
  - CVE-2015-0222
  credit:
  - OSSIndex
  references:
  - http://advisories.mageia.org/MGASA-2015-0026.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148485.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148608.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148696.html
  - http://lists.opensuse.org/opensuse-updates/2015-04/msg00001.html
  - http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html
  - http://secunia.com/advisories/62285
  - http://secunia.com/advisories/62309
  - http://ubuntu.com/usn/usn-2469-1
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:109
  - https://www.djangoproject.com/weblog/2015/jan/13/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-01-16
  title: "[CVE-2015-0221]  Resource Management Errors"
  description: The django.views.static.serve view in Django before 1.4.18, 1.6.x before
    1.6.10, and 1.7.x before 1.7.3 reads files an entire line at a time, which allows
    remote attackers to cause a denial of service (memory consumption) via a long
    line in a file.
  affected_package: Django
  vulnerable_versions:
  - 1.4.17
  - 1.6.7
  - '1.6'
  - 1.6.8
  - 1.6.1
  - 1.6.9
  - 1.6.2
  - '1.7'
  - 1.6.3
  - 1.7.1
  - 1.6.4
  - 1.7.2
  - 1.6.5
  - 1.6.6
  package_manager: pypi
  cve:
  - CVE-2015-0221
  credit:
  - OSSIndex
  references:
  - http://advisories.mageia.org/MGASA-2015-0026.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148485.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148608.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148696.html
  - http://lists.opensuse.org/opensuse-updates/2015-04/msg00001.html
  - http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html
  - http://secunia.com/advisories/62285
  - http://secunia.com/advisories/62309
  - http://secunia.com/advisories/62718
  - http://ubuntu.com/usn/usn-2469-1
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:036
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:109
  - https://www.djangoproject.com/weblog/2015/jan/13/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-01-16
  title: '[CVE-2015-0220]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: The django.util.http.is_safe_url function in Django before 1.4.18,
    1.6.x before 1.6.10, and 1.7.x before 1.7.3 does not properly handle leading whitespaces,
    which allows remote attackers to conduct cross-site scripting (XSS) attacks via
    a crafted URL, related to redirect URLs, as demonstrated by a "\njavascript:"
    URL.
  affected_package: Django
  vulnerable_versions:
  - 1.6.5
  - 1.6.6
  - 1.4.17
  - 1.6.7
  - '1.6'
  - 1.6.8
  - 1.6.1
  - 1.6.9
  - 1.6.2
  - '1.7'
  - 1.7.1
  - 1.6.3
  - 1.7.2
  - 1.6.4
  package_manager: pypi
  cve:
  - CVE-2015-0220
  credit:
  - OSSIndex
  references:
  - http://advisories.mageia.org/MGASA-2015-0026.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148485.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148608.html
  - http://lists.opensuse.org/opensuse-updates/2015-04/msg00001.html
  - http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html
  - http://secunia.com/advisories/62285
  - http://secunia.com/advisories/62309
  - http://secunia.com/advisories/62718
  - http://ubuntu.com/usn/usn-2469-1
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:036
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:109
  - https://www.djangoproject.com/weblog/2015/jan/13/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-01-16
  title: "[CVE-2015-0219]  Code"
  description: Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 allows
    remote attackers to spoof WSGI headers by using an _ (underscore) character instead
    of a - (dash) character in an HTTP header, as demonstrated by an X-Auth_User header.
  affected_package: Django
  vulnerable_versions:
  - 1.6.3
  - 1.7.1
  - 1.6.4
  - 1.7.2
  - 1.6.5
  - 1.6.6
  - 1.4.17
  - 1.6.7
  - '1.6'
  - 1.6.8
  - 1.6.1
  - 1.6.9
  - 1.6.2
  - '1.7'
  package_manager: pypi
  cve:
  - CVE-2015-0219
  credit:
  - OSSIndex
  references:
  - http://advisories.mageia.org/MGASA-2015-0026.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148485.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148608.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-January/148696.html
  - http://lists.opensuse.org/opensuse-updates/2015-04/msg00001.html
  - http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html
  - http://secunia.com/advisories/62285
  - http://secunia.com/advisories/62309
  - http://secunia.com/advisories/62718
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:036
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:109
  - http://www.ubuntu.com/usn/USN-2469-1
  - https://www.djangoproject.com/weblog/2015/jan/13/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2016-12-09
  title: "[CVE-2016-9013] Django 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x
    before 1.10.3 use a ..."
  description: Django 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before
    1.10.3 use a hardcoded password for a temporary database user created when running
    tests with an Oracle database, which makes it easier for remote attackers to obtain
    access to the database server by leveraging failure to manually specify a password
    in the database settings TEST dictionary.
  affected_package: Django
  vulnerable_versions:
  - 1.8.12
  - 1.8.6
  - 1.9.3
  - '1.10'
  - 1.8.13
  - 1.8.7
  - 1.9.4
  - 1.10.1
  - 1.8.14
  - 1.8.8
  - 1.9.5
  - 1.10.2
  - 1.8.15
  - 1.8.9
  - 1.9.6
  - '1.8'
  - 1.8.2
  - '1.9'
  - 1.9.7
  - 1.8.1
  - 1.8.3
  - 1.9.1
  - 1.9.8
  - 1.8.10
  - 1.8.4
  - 1.9.10
  - 1.9.9
  - 1.8.11
  - 1.8.5
  - 1.9.2
  package_manager: pypi
  cve:
  - CVE-2016-9013
  credit:
  - OSSIndex
  references:
  - http://www.debian.org/security/2017/dsa-3835
  - http://www.securityfocus.com/bid/94069
  - http://www.securitytracker.com/id/1037159
  - http://www.ubuntu.com/usn/USN-3115-1
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OG5ROMUPS6C7BXELD3TAUUH7OBYV56WQ/
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QXDKJYHN74BWY3P7AR2UZDVJREQMRE6S/
  - https://www.djangoproject.com/weblog/2016/nov/01/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2016-12-09
  title: "[CVE-2016-9014]  Permissions, Privileges, and Access Controls"
  description: Django before 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x
    before 1.10.3, when settings.DEBUG is True, allow remote attackers to conduct
    DNS rebinding attacks by leveraging failure to validate the HTTP Host header against
    settings.ALLOWED_HOSTS.
  affected_package: Django
  vulnerable_versions:
  - 1.10.1
  - 1.8.14
  - 1.8.8
  - 1.9.5
  - 1.10.2
  - 1.8.15
  - 1.8.9
  - 1.9.6
  - 1.9.7
  - '1.8'
  - 1.8.2
  - '1.9'
  - 1.9.8
  - 1.8.1
  - 1.8.3
  - 1.9.1
  - 1.9.9
  - 1.8.10
  - 1.8.4
  - 1.9.10
  - 1.8.11
  - 1.8.5
  - 1.9.2
  - 1.8.12
  - 1.8.6
  - 1.9.3
  - '1.10'
  - 1.8.13
  - 1.8.7
  - 1.9.4
  package_manager: pypi
  cve:
  - CVE-2016-9014
  credit:
  - OSSIndex
  references:
  - http://www.debian.org/security/2017/dsa-3835
  - http://www.securityfocus.com/bid/94068
  - http://www.securitytracker.com/id/1037159
  - http://www.ubuntu.com/usn/USN-3115-1
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OG5ROMUPS6C7BXELD3TAUUH7OBYV56WQ/
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QXDKJYHN74BWY3P7AR2UZDVJREQMRE6S/
  - https://www.djangoproject.com/weblog/2016/nov/01/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-12-07
  title: "[CVE-2015-8213]  Information Exposure"
  description: The get_format function in utils/formats.py in Django before 1.7.x
    before 1.7.11, 1.8.x before 1.8.7, and 1.9.x before 1.9rc2 might allow remote
    attackers to obtain sensitive application secrets via a settings key in place
    of a date/time format setting, as demonstrated by SECRET_KEY.
  affected_package: Django
  vulnerable_versions:
  - 1.8.4
  - 1.8.5
  - 1.8.6
  - 1.7.10
  - 1.9.0
  - 1.8.0
  - 1.8.1
  - 1.8.2
  - 1.8.3
  package_manager: pypi
  cve:
  - CVE-2015-8213
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-December/173375.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-December/174770.html
  - http://lists.opensuse.org/opensuse-updates/2015-12/msg00014.html
  - http://lists.opensuse.org/opensuse-updates/2015-12/msg00017.html
  - http://rhn.redhat.com/errata/RHSA-2016-0129.html
  - http://rhn.redhat.com/errata/RHSA-2016-0156.html
  - http://rhn.redhat.com/errata/RHSA-2016-0157.html
  - http://rhn.redhat.com/errata/RHSA-2016-0158.html
  - http://www.debian.org/security/2015/dsa-3404
  - http://www.securityfocus.com/bid/77750
  - http://www.securitytracker.com/id/1034237
  - http://www.ubuntu.com/usn/USN-2816-1
  - https://github.com/django/django/commit/316bc3fc9437c5960c24baceb93c73f1939711e4
  - https://www.djangoproject.com/weblog/2015/nov/24/security-releases-issued/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-07-14
  title: "[CVE-2015-5145]  Resource Management Errors"
  description: validators.URLValidator in Django 1.8.x before 1.8.3 allows remote
    attackers to cause a denial of service (CPU consumption) via unspecified vectors.
  affected_package: Django
  vulnerable_versions:
  - 1.8.0
  - 1.8.1
  - 1.8.2
  package_manager: pypi
  cve:
  - CVE-2015-5145
  credit:
  - OSSIndex
  references:
  - http://www.securityfocus.com/bid/75691
  - http://www.securitytracker.com/id/1032820
  - https://security.gentoo.org/glsa/201510-06
  - https://www.djangoproject.com/weblog/2015/jul/08/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-06-02
  title: "[CVE-2015-3982] The session.flush function in the cached&#95;db backend
    in Django 1.8.x before 1.8.2..."
  description: The session.flush function in the cached_db backend in Django 1.8.x
    before 1.8.2 does not properly flush the session, which allows remote attackers
    to hijack user sessions via an empty string in the session key.
  affected_package: Django
  vulnerable_versions:
  - 1.8.0
  - 1.8.1
  package_manager: pypi
  cve:
  - CVE-2015-3982
  credit:
  - OSSIndex
  references:
  - http://www.securityfocus.com/bid/74960
  - https://www.djangoproject.com/weblog/2015/may/20/security-release/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2016-04-08
  title: "[CVE-2016-2513]  Information Exposure"
  description: The password hasher in contrib/auth/hashers.py in Django before 1.8.10
    and 1.9.x before 1.9.3 allows remote attackers to enumerate users via a timing
    attack involving login requests.
  affected_package: Django
  vulnerable_versions:
  - 1.8.9
  - '1.9'
  - 1.9.1
  - 1.9.2
  package_manager: pypi
  cve:
  - CVE-2016-2513
  credit:
  - OSSIndex
  references:
  - http://rhn.redhat.com/errata/RHSA-2016-0502.html
  - http://rhn.redhat.com/errata/RHSA-2016-0504.html
  - http://rhn.redhat.com/errata/RHSA-2016-0505.html
  - http://rhn.redhat.com/errata/RHSA-2016-0506.html
  - http://www.debian.org/security/2016/dsa-3544
  - http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html
  - http://www.securityfocus.com/bid/83878
  - http://www.securitytracker.com/id/1035152
  - http://www.ubuntu.com/usn/USN-2915-1
  - http://www.ubuntu.com/usn/USN-2915-2
  - http://www.ubuntu.com/usn/USN-2915-3
  - https://github.com/django/django/commit/67b46ba7016da2d259c1ecc7d666d11f5e1cfaab
  - https://www.djangoproject.com/weblog/2016/mar/01/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2016-04-08
  title: '[CVE-2016-2512]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x
    before 1.9.3 allows remote attackers to redirect users to arbitrary web sites
    and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks
    via a URL containing basic authentication, as demonstrated by http://mysite.example.com\@attacker.com.
  affected_package: Django
  vulnerable_versions:
  - 1.8.9
  - '1.9'
  - 1.9.1
  - 1.9.2
  package_manager: pypi
  cve:
  - CVE-2016-2512
  credit:
  - OSSIndex
  references:
  - http://rhn.redhat.com/errata/RHSA-2016-0502.html
  - http://rhn.redhat.com/errata/RHSA-2016-0504.html
  - http://rhn.redhat.com/errata/RHSA-2016-0505.html
  - http://rhn.redhat.com/errata/RHSA-2016-0506.html
  - http://www.debian.org/security/2016/dsa-3544
  - http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html
  - http://www.securityfocus.com/bid/83879
  - http://www.securitytracker.com/id/1035152
  - http://www.ubuntu.com/usn/USN-2915-1
  - http://www.ubuntu.com/usn/USN-2915-2
  - http://www.ubuntu.com/usn/USN-2915-3
  - https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0
  - https://www.djangoproject.com/weblog/2016/mar/01/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-03-25
  title: "[CVE-2015-2316]  Resource Management Errors"
  description: The utils.html.strip_tags function in Django 1.6.x before 1.6.11, 1.7.x
    before 1.7.7, and 1.8.x before 1.8c1, when using certain versions of Python, allows
    remote attackers to cause a denial of service (infinite loop) by increasing the
    length of the input string.
  affected_package: Django
  vulnerable_versions:
  - 1.6.10
  - 1.6.9
  - 1.8.0
  - 1.6.2
  - '1.7'
  - 1.6.3
  - 1.7.1
  - 1.6.4
  - 1.7.2
  - 1.6.5
  - 1.7.3
  - 1.6.6
  - 1.7.4
  - '1.6'
  - 1.6.7
  - 1.7.5
  - 1.6.1
  - 1.6.8
  - 1.7.6
  package_manager: pypi
  cve:
  - CVE-2015-2316
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2015-April/155421.html
  - http://lists.opensuse.org/opensuse-updates/2015-04/msg00001.html
  - http://www.oracle.com/technetwork/topics/security/bulletinapr2015-2511959.html
  - http://www.securityfocus.com/bid/73322
  - http://www.ubuntu.com/usn/USN-2539-1
  - https://www.djangoproject.com/weblog/2015/mar/18/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2015-03-12
  title: '[CVE-2015-2241]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: Cross-site scripting (XSS) vulnerability in the contents function in
    admin/helpers.py in Django before 1.7.6 and 1.8 before 1.8b2 allows remote attackers
    to inject arbitrary web script or HTML via a model attribute in ModelAdmin.readonly_fields,
    as demonstrated by a @property.
  affected_package: Django
  vulnerable_versions:
  - 1.7.5
  - '1.8'
  package_manager: pypi
  cve:
  - CVE-2015-2241
  credit:
  - OSSIndex
  references:
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:109
  - http://www.securityfocus.com/bid/73095
  - https://code.djangoproject.com/ticket/24461
  - https://www.djangoproject.com/weblog/2015/mar/09/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2016-08-05
  title: '[CVE-2016-6186]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: Cross-site scripting (XSS) vulnerability in the dismissChangeRelatedObjectPopup
    function in contrib/admin/static/admin/js/admin/RelatedObjectLookups.js in Django
    before 1.8.14, 1.9.x before 1.9.8, and 1.10.x before 1.10rc1 allows remote attackers
    to inject arbitrary web script or HTML via vectors involving unsafe usage of Element.innerHTML.
  affected_package: Django
  vulnerable_versions:
  - 1.8.13
  - 1.9.1
  - '1.9'
  - 1.9.2
  - 1.9.0
  - 1.9.3
  - 1.9.4
  - 1.9.5
  - 1.9.6
  - 1.9.7
  - '1.10'
  package_manager: pypi
  cve:
  - CVE-2016-6186
  credit:
  - OSSIndex
  references:
  - http://packetstormsecurity.com/files/137965/Django-3.3.0-Script-Insertion.html
  - http://rhn.redhat.com/errata/RHSA-2016-1594.html
  - http://rhn.redhat.com/errata/RHSA-2016-1595.html
  - http://rhn.redhat.com/errata/RHSA-2016-1596.html
  - http://seclists.org/fulldisclosure/2016/Jul/53
  - http://www.debian.org/security/2016/dsa-3622
  - http://www.securityfocus.com/archive/1/archive/1/538947/100/0/threaded
  - http://www.securityfocus.com/bid/92058
  - http://www.securitytracker.com/id/1036338
  - http://www.ubuntu.com/usn/USN-3039-1
  - http://www.vulnerability-lab.com/get_content.php?id=1869
  - https://github.com/django/django/commit/d03bf6fe4e9bf5b07de62c1a271c4b41a7d3d158
  - https://github.com/django/django/commit/f68e5a99164867ab0e071a936470958ed867479d
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DMLLFAUT4J4IP4P2KI4NOVWRMHA22WUJ/
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KHHPN6MISX5I6UTXQHYLPTLEEUE6WDXW/
  - https://www.djangoproject.com/weblog/2016/jul/18/security-releases/
  - https://www.exploit-db.com/exploits/40129/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2016-02-08
  title: "[CVE-2016-2048]  Improper Access Control"
  description: Django 1.9.x before 1.9.2, when ModelAdmin.save_as is set to True,
    allows remote authenticated users to bypass intended access restrictions and create
    ModelAdmin objects via the "Save as New" option when editing objects and leveraging
    the "change" permission.
  affected_package: Django
  vulnerable_versions:
  - '1.9'
  - 1.9.1
  package_manager: pypi
  cve:
  - CVE-2016-2048
  credit:
  - OSSIndex
  references:
  - http://www.securityfocus.com/bid/82329
  - http://www.securitytracker.com/id/1034894
  - https://www.djangoproject.com/weblog/2016/feb/01/releases-192-and-189/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2016-10-03
  title: "[CVE-2016-7401] The cookie parsing code in Django before 1.8.15 and 1.9.x
    before 1.9.10, when us..."
  description: The cookie parsing code in Django before 1.8.15 and 1.9.x before 1.9.10,
    when used on a site with Google Analytics, allows remote attackers to bypass an
    intended CSRF protection mechanism by setting arbitrary cookies.
  affected_package: Django
  vulnerable_versions:
  - 1.9.5
  - 1.9.6
  - 1.8.14
  - 1.9.7
  - 1.9.0
  - 1.9.8
  - 1.9.1
  - 1.9.9
  - 1.9.2
  - 1.9.3
  - 1.9.4
  package_manager: pypi
  cve:
  - CVE-2016-7401
  credit:
  - OSSIndex
  references:
  - http://rhn.redhat.com/errata/RHSA-2016-2038.html
  - http://rhn.redhat.com/errata/RHSA-2016-2039.html
  - http://rhn.redhat.com/errata/RHSA-2016-2040.html
  - http://rhn.redhat.com/errata/RHSA-2016-2041.html
  - http://rhn.redhat.com/errata/RHSA-2016-2042.html
  - http://rhn.redhat.com/errata/RHSA-2016-2043.html
  - http://www.debian.org/security/2016/dsa-3678
  - http://www.securityfocus.com/bid/93182
  - http://www.securitytracker.com/id/1036899
  - http://www.ubuntu.com/usn/USN-3089-1
  - https://www.djangoproject.com/weblog/2016/sep/26/security-releases/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2013-09-23
  title: "[CVE-2013-1443]  Improper Authentication"
  description: The authentication framework (django.contrib.auth) in Django 1.4.x
    before 1.4.8, 1.5.x before 1.5.4, and 1.6.x before 1.6 beta 4 allows remote attackers
    to cause a denial of service (CPU consumption) via a long password which is then
    hashed.
  affected_package: Django
  vulnerable_versions:
  - '1.6'
  - 1.4.4
  - 1.4.5
  - 1.4.6
  - 1.4.7
  - '1.5'
  - 1.5.1
  - '1.4'
  - 1.5.2
  - 1.4.1
  - 1.5.3
  - 1.4.2
  package_manager: pypi
  cve:
  - CVE-2013-1443
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2013-10/msg00015.html
  - http://lists.opensuse.org/opensuse-updates/2013-11/msg00035.html
  - http://python.6.x6.nabble.com/Set-a-reasonable-upper-bound-on-password-length-td5032218.html
  - http://www.debian.org/security/2013/dsa-2758
  - https://www.djangoproject.com/weblog/2013/sep/15/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2013-10-04
  title: '[CVE-2013-6044]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: 'The is_safe_url function in utils/http.py in Django 1.4.x before 1.4.6,
    1.5.x before 1.5.2, and 1.6 before beta 2 treats a URL''s scheme as safe even
    if it is not HTTP or HTTPS, which might introduce cross-site scripting (XSS) or
    other vulnerabilities into Django applications that use this function, as demonstrated
    by "the login view in django.contrib.auth.views" and the javascript: scheme.'
  affected_package: Django
  vulnerable_versions:
  - '1.5'
  - 1.5.1
  - '1.6'
  - '1.4'
  - 1.4.1
  - 1.4.2
  - 1.4.4
  - 1.4.5
  package_manager: pypi
  cve:
  - CVE-2013-6044
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2013-10/msg00015.html
  - http://rhn.redhat.com/errata/RHSA-2013-1521.html
  - http://seclists.org/oss-sec/2013/q3/369
  - http://seclists.org/oss-sec/2013/q3/411
  - http://secunia.com/advisories/54476
  - http://www.debian.org/security/2013/dsa-2740
  - http://www.securityfocus.com/bid/61777
  - http://www.securitytracker.com/id/1028915
  - http://xforce.iss.net/xforce/xfdb/86437
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/86437
  - https://github.com/django/django/commit/1a274ccd6bc1afbdac80344c9b6e5810c1162b5f
  - https://github.com/django/django/commit/ae3535169af804352517b7fea94a42a1c9c4b762
  - https://github.com/django/django/commit/ec67af0bd609c412b76eaa4cc89968a2a8e5ad6a
  - https://www.djangoproject.com/weblog/2013/aug/13/security-releases-issued
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2013-09-16
  title: '[CVE-2013-4315]  Improper Limitation of a Pathname to a Restricted Directory
    ("Path Traversal")'
  description: Directory traversal vulnerability in Django 1.4.x before 1.4.7, 1.5.x
    before 1.5.3, and 1.6.x before 1.6 beta 3 allows remote attackers to read arbitrary
    files via a file path in the ALLOWED_INCLUDE_ROOTS setting followed by a .. (dot
    dot) in a ssi template tag.
  affected_package: Django
  vulnerable_versions:
  - '1.5'
  - 1.5.1
  - '1.4'
  - '1.6'
  - 1.4.1
  - 1.4.2
  - 1.4.4
  - 1.4.5
  - 1.4.6
  package_manager: pypi
  cve:
  - CVE-2013-4315
  credit:
  - OSSIndex
  references:
  - http://lists.opensuse.org/opensuse-updates/2013-10/msg00015.html
  - http://rhn.redhat.com/errata/RHSA-2013-1521.html
  - http://secunia.com/advisories/54772
  - http://secunia.com/advisories/54828
  - http://www.debian.org/security/2013/dsa-2755
  - https://www.djangoproject.com/weblog/2013/sep/10/security-releases-issued/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2013-10-04
  title: '[CVE-2013-4249]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: Cross-site scripting (XSS) vulnerability in the AdminURLFieldWidget
    widget in contrib/admin/widgets.py in Django 1.5.x before 1.5.2 and 1.6.x before
    1.6 beta 2 allows remote attackers to inject arbitrary web script or HTML via
    a URLField.
  affected_package: Django
  vulnerable_versions:
  - '1.5'
  - 1.5.1
  - '1.6'
  package_manager: pypi
  cve:
  - CVE-2013-4249
  credit:
  - OSSIndex
  references:
  - http://seclists.org/oss-sec/2013/q3/369
  - http://seclists.org/oss-sec/2013/q3/411
  - http://secunia.com/advisories/54476
  - http://www.securitytracker.com/id/1028915
  - http://xforce.iss.net/xforce/xfdb/86438
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/86438
  - https://github.com/django/django/commit/90363e388c61874add3f3557ee654a996ec75d78
  - https://github.com/django/django/commit/cbe6d5568f4f5053ed7228ca3c3d0cce77cf9560
  - https://www.djangoproject.com/weblog/2013/aug/13/security-releases-issued
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2013-05-02
  title: "[CVE-2013-0306]  Numeric Errors"
  description: The form library in Django 1.3.x before 1.3.6, 1.4.x before 1.4.4,
    and 1.5 before release candidate 2 allows remote attackers to bypass intended
    resource limits for formsets and cause a denial of service (memory consumption)
    or trigger server errors via a modified max_num parameter.
  affected_package: Django
  vulnerable_versions:
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - '1.4'
  - 1.4.1
  - 1.4.2
  - '1.5'
  - '1.3'
  package_manager: pypi
  cve:
  - CVE-2013-0306
  credit:
  - OSSIndex
  references:
  - http://rhn.redhat.com/errata/RHSA-2013-0670.html
  - http://ubuntu.com/usn/usn-1757-1
  - http://www.debian.org/security/2013/dsa-2634
  - https://www.djangoproject.com/weblog/2013/feb/19/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2013-05-02
  title: "[CVE-2013-0305]  Information Exposure"
  description: The administrative interface for Django 1.3.x before 1.3.6, 1.4.x before
    1.4.4, and 1.5 before release candidate 2 does not check permissions for the history
    view, which allows remote authenticated administrators to obtain sensitive object
    history information.
  affected_package: Django
  vulnerable_versions:
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - '1.4'
  - 1.4.1
  - 1.4.2
  - '1.5'
  - '1.3'
  package_manager: pypi
  cve:
  - CVE-2013-0305
  credit:
  - OSSIndex
  references:
  - http://rhn.redhat.com/errata/RHSA-2013-0670.html
  - http://ubuntu.com/usn/usn-1757-1
  - http://www.debian.org/security/2013/dsa-2634
  - https://www.djangoproject.com/weblog/2013/feb/19/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2012-11-18
  title: "[CVE-2012-4520]  Improper Input Validation"
  description: The django.http.HttpRequest.get_host function in Django 1.3.x before
    1.3.4 and 1.4.x before 1.4.2 allows remote attackers to generate and display arbitrary
    URLs via crafted username and password Host header values.
  affected_package: Django
  vulnerable_versions:
  - '1.3'
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - '1.4'
  - 1.4.1
  package_manager: pypi
  cve:
  - CVE-2012-4520
  credit:
  - OSSIndex
  references:
  - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=691145
  - http://lists.fedoraproject.org/pipermail/package-announce/2012-October/090666.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2012-October/090904.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2012-October/090970.html
  - http://secunia.com/advisories/51033
  - http://secunia.com/advisories/51314
  - http://securitytracker.com/id?1027708
  - http://ubuntu.com/usn/usn-1632-1
  - http://ubuntu.com/usn/usn-1757-1
  - http://www.debian.org/security/2013/dsa-2634
  - http://www.openwall.com/lists/oss-security/2012/10/30/4
  - http://www.osvdb.org/86493
  - https://bugzilla.redhat.com/show_bug.cgi?id=865164
  - https://github.com/django/django/commit/92d3430f12171f16f566c9050c40feefb830a4a3
  - https://github.com/django/django/commit/9305c0e12d43c4df999c3301a1f0c742264a657e
  - https://github.com/django/django/commit/b45c377f8f488955e0c7069cad3f3dd21910b071
  - https://www.djangoproject.com/weblog/2012/oct/17/security/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2012-07-31
  title: "[CVE-2012-3444]  Improper Restriction of Operations within the Bounds of
    a Memory Buffer"
  description: The get_image_dimensions function in the image-handling functionality
    in Django before 1.3.2 and 1.4.x before 1.4.1 uses a constant chunk size in all
    attempts to determine dimensions, which allows remote attackers to cause a denial
    of service (process or thread consumption) via a large TIFF image.
  affected_package: Django
  vulnerable_versions:
  - 1.0.1
  - 1.2.2
  - 1.0.2
  - 1.2.4
  - '1.1'
  - 1.2.5
  - 1.1.2
  - 1.2.6
  - 1.1.3
  - 1.2.7
  - '0.95'
  - 1.1.4
  - '1.3'
  - '0.96'
  - '1.2'
  - '1.4'
  - '1.0'
  - 1.2-alpha1
  package_manager: pypi
  cve:
  - CVE-2012-3444
  credit:
  - OSSIndex
  references:
  - http://www.debian.org/security/2012/dsa-2529
  - http://www.mandriva.com/security/advisories?name=MDVSA-2012:143
  - http://www.openwall.com/lists/oss-security/2012/07/31/1
  - http://www.openwall.com/lists/oss-security/2012/07/31/2
  - http://www.ubuntu.com/usn/USN-1560-1
  - https://www.djangoproject.com/weblog/2012/jul/30/security-releases-issued/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2012-07-31
  title: "[CVE-2012-3443]  Improper Input Validation"
  description: The django.forms.ImageField class in the form system in Django before
    1.3.2 and 1.4.x before 1.4.1 completely decompresses image data during image validation,
    which allows remote attackers to cause a denial of service (memory consumption)
    by uploading an image file.
  affected_package: Django
  vulnerable_versions:
  - '1.1'
  - 1.2.5
  - 1.1.2
  - 1.2.6
  - 1.1.3
  - 1.2.7
  - '0.95'
  - 1.1.4
  - '1.3'
  - '0.96'
  - '1.2'
  - '1.4'
  - '1.0'
  - 1.2-alpha1
  - 1.0.1
  - 1.2.2
  - 1.0.2
  - 1.2.4
  package_manager: pypi
  cve:
  - CVE-2012-3443
  credit:
  - OSSIndex
  references:
  - http://www.debian.org/security/2012/dsa-2529
  - http://www.mandriva.com/security/advisories?name=MDVSA-2012:143
  - http://www.openwall.com/lists/oss-security/2012/07/31/1
  - http://www.openwall.com/lists/oss-security/2012/07/31/2
  - http://www.ubuntu.com/usn/USN-1560-1
  - https://www.djangoproject.com/weblog/2012/jul/30/security-releases-issued/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2012-07-31
  title: '[CVE-2012-3442]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: 'The (1) django.http.HttpResponseRedirect and (2) django.http.HttpResponsePermanentRedirect
    classes in Django before 1.3.2 and 1.4.x before 1.4.1 do not validate the scheme
    of a redirect target, which might allow remote attackers to conduct cross-site
    scripting (XSS) attacks via a data: URL.'
  affected_package: Django
  vulnerable_versions:
  - 1.2.7
  - 1.1.3
  - '1.3'
  - '0.95'
  - 1.1.4
  - '1.4'
  - '0.96'
  - '1.2'
  - '1.0'
  - 1.2-alpha1
  - 1.0.1
  - 1.2.2
  - 1.0.2
  - 1.2.4
  - 1.2.5
  - '1.1'
  - 1.2.6
  - 1.1.2
  package_manager: pypi
  cve:
  - CVE-2012-3442
  credit:
  - OSSIndex
  references:
  - http://www.debian.org/security/2012/dsa-2529
  - http://www.mandriva.com/security/advisories?name=MDVSA-2012:143
  - http://www.openwall.com/lists/oss-security/2012/07/31/1
  - http://www.openwall.com/lists/oss-security/2012/07/31/2
  - http://www.ubuntu.com/usn/USN-1560-1
  - https://www.djangoproject.com/weblog/2012/jul/30/security-releases-issued/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-10-19
  title: "[CVE-2011-4140]  Cross-Site Request Forgery (CSRF)"
  description: The CSRF protection mechanism in Django through 1.2.7 and 1.3.x through
    1.3.1 does not properly handle web-server configurations supporting arbitrary
    HTTP Host headers, which allows remote attackers to trigger unauthenticated forged
    requests via vectors involving a DNS CNAME record and a web page containing JavaScript
    code.
  affected_package: Django
  vulnerable_versions:
  - '0.95'
  - 1.1.2
  - 1.2.6
  - 0.95.1
  - 1.1.3
  - '1.3'
  - '0.96'
  - '1.2'
  - '1.0'
  - 1.2.1
  - 1.0.1
  - 1.2.2
  - 1.0.2
  - 1.2.3
  - '1.1'
  - 1.2.4
  - '0.91'
  - 1.1.0
  - 1.2.5
  package_manager: pypi
  cve:
  - CVE-2011-4140
  credit:
  - OSSIndex
  references:
  - http://openwall.com/lists/oss-security/2011/09/11/1
  - http://openwall.com/lists/oss-security/2011/09/13/2
  - http://secunia.com/advisories/46614
  - http://www.debian.org/security/2011/dsa-2332
  - https://bugzilla.redhat.com/show_bug.cgi?id=737366
  - https://www.djangoproject.com/weblog/2011/sep/09/
  - https://www.djangoproject.com/weblog/2011/sep/10/127/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-10-19
  title: "[CVE-2011-4139]  Improper Input Validation"
  description: Django before 1.2.7 and 1.3.x before 1.3.1 uses a request's HTTP Host
    header to construct a full URL in certain circumstances, which allows remote attackers
    to conduct cache poisoning attacks via a crafted request.
  affected_package: Django
  vulnerable_versions:
  - '1.0'
  - 1.2.1
  - 1.0.1
  - 1.2.2
  - 1.0.2
  - 1.2.3
  - '1.1'
  - 1.2.4
  - '0.91'
  - 1.1.0
  - 1.2.5
  - '0.95'
  - 1.1.2
  - 1.2.6
  - 0.95.1
  - 1.1.3
  - '1.3'
  - '0.96'
  - '1.2'
  package_manager: pypi
  cve:
  - CVE-2011-4139
  credit:
  - OSSIndex
  references:
  - http://openwall.com/lists/oss-security/2011/09/11/1
  - http://openwall.com/lists/oss-security/2011/09/13/2
  - http://secunia.com/advisories/46614
  - http://www.debian.org/security/2011/dsa-2332
  - https://bugzilla.redhat.com/show_bug.cgi?id=737366
  - https://www.djangoproject.com/weblog/2011/sep/09/
  - https://www.djangoproject.com/weblog/2011/sep/10/127/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-10-19
  title: "[CVE-2011-4138]  Improper Input Validation"
  description: The verify_exists functionality in the URLField implementation in Django
    before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's validity through
    a HEAD request, but then uses a GET request for the new target URL in the case
    of a redirect, which might allow remote attackers to trigger arbitrary GET requests
    with an unintended source IP address via a crafted Location header.
  affected_package: Django
  vulnerable_versions:
  - '1.1'
  - 1.2.4
  - 1.1.0
  - 1.2.5
  - '0.91'
  - 1.1.2
  - 1.2.6
  - '0.95'
  - 1.1.3
  - '1.3'
  - 0.95.1
  - '0.96'
  - '1.2'
  - '1.0'
  - 1.2.1
  - 1.0.1
  - 1.2.2
  - 1.0.2
  - 1.2.3
  package_manager: pypi
  cve:
  - CVE-2011-4138
  credit:
  - OSSIndex
  references:
  - http://openwall.com/lists/oss-security/2011/09/11/1
  - http://openwall.com/lists/oss-security/2011/09/13/2
  - http://secunia.com/advisories/46614
  - http://www.debian.org/security/2011/dsa-2332
  - https://bugzilla.redhat.com/show_bug.cgi?id=737366
  - https://www.djangoproject.com/weblog/2011/sep/09/
  - https://www.djangoproject.com/weblog/2011/sep/10/127/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-10-19
  title: "[CVE-2011-4137]  Resource Management Errors"
  description: The verify_exists functionality in the URLField implementation in Django
    before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access
    to an arbitrary URL with no timeout, which allows remote attackers to cause a
    denial of service (resource consumption) via a URL associated with (1) a slow
    response, (2) a completed TCP connection with no application data sent, or (3)
    a large amount of application data, a related issue to CVE-2011-1521.
  affected_package: Django
  vulnerable_versions:
  - 0.95.1
  - 1.1.3
  - '1.3'
  - '0.96'
  - '1.2'
  - '1.0'
  - 1.2.1
  - 1.0.1
  - 1.2.2
  - 1.0.2
  - 1.2.3
  - '1.1'
  - 1.2.4
  - '0.91'
  - 1.1.0
  - 1.2.5
  - '0.95'
  - 1.1.2
  - 1.2.6
  package_manager: pypi
  cve:
  - CVE-2011-4137
  credit:
  - OSSIndex
  references:
  - http://openwall.com/lists/oss-security/2011/09/11/1
  - http://openwall.com/lists/oss-security/2011/09/13/2
  - http://openwall.com/lists/oss-security/2011/09/15/5
  - http://secunia.com/advisories/46614
  - http://www.debian.org/security/2011/dsa-2332
  - https://bugzilla.redhat.com/show_bug.cgi?id=737366
  - https://www.djangoproject.com/weblog/2011/sep/09/
  - https://www.djangoproject.com/weblog/2011/sep/10/127/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-10-19
  title: "[CVE-2011-4136]  Improper Input Validation"
  description: django.contrib.sessions in Django before 1.2.7 and 1.3.x before 1.3.1,
    when session data is stored in the cache, uses the root namespace for both session
    identifiers and application-data keys, which allows remote attackers to modify
    a session by triggering use of a key that is equal to that session's identifier.
  affected_package: Django
  vulnerable_versions:
  - 1.0.1
  - 1.2.2
  - 1.0.2
  - 1.2.3
  - '1.1'
  - 1.2.4
  - '0.91'
  - 1.1.0
  - 1.2.5
  - '0.95'
  - 1.1.2
  - 1.2.6
  - 0.95.1
  - 1.1.3
  - '1.3'
  - '0.96'
  - '1.2'
  - '1.0'
  - 1.2.1
  package_manager: pypi
  cve:
  - CVE-2011-4136
  credit:
  - OSSIndex
  references:
  - http://openwall.com/lists/oss-security/2011/09/11/1
  - http://openwall.com/lists/oss-security/2011/09/13/2
  - http://secunia.com/advisories/46614
  - http://www.debian.org/security/2011/dsa-2332
  - https://bugzilla.redhat.com/show_bug.cgi?id=737366
  - https://www.djangoproject.com/weblog/2011/sep/09/
  - https://www.djangoproject.com/weblog/2011/sep/10/127/
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-02-14
  title: '[CVE-2011-0697]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: Cross-site scripting (XSS) vulnerability in Django 1.1.x before 1.1.4
    and 1.2.x before 1.2.5 might allow remote attackers to inject arbitrary web script
    or HTML via a filename associated with a file upload.
  affected_package: Django
  vulnerable_versions:
  - '1.2'
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - '1.1'
  - 1.2.4
  - 1.1.0
  - 1.1.2
  - 1.1.3
  package_manager: pypi
  cve:
  - CVE-2011-0697
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2011-February/054207.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2011-February/054208.html
  - http://openwall.com/lists/oss-security/2011/02/09/6
  - http://secunia.com/advisories/43230
  - http://secunia.com/advisories/43297
  - http://secunia.com/advisories/43382
  - http://secunia.com/advisories/43426
  - http://www.debian.org/security/2011/dsa-2163
  - http://www.djangoproject.com/weblog/2011/feb/08/security/
  - http://www.mandriva.com/security/advisories?name=MDVSA-2011:031
  - http://www.securityfocus.com/bid/46296
  - http://www.ubuntu.com/usn/USN-1066-1
  - http://www.vupen.com/english/advisories/2011/0372
  - http://www.vupen.com/english/advisories/2011/0388
  - http://www.vupen.com/english/advisories/2011/0429
  - http://www.vupen.com/english/advisories/2011/0439
  - http://www.vupen.com/english/advisories/2011/0441
  - https://bugzilla.redhat.com/show_bug.cgi?id=676359
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-02-14
  title: "[CVE-2011-0696]  Cross-Site Request Forgery (CSRF)"
  description: Django 1.1.x before 1.1.4 and 1.2.x before 1.2.5 does not properly
    validate HTTP requests that contain an X-Requested-With header, which makes it
    easier for remote attackers to conduct cross-site request forgery (CSRF) attacks
    via forged AJAX requests that leverage a "combination of browser plugins and redirects,"
    a related issue to CVE-2011-0447.
  affected_package: Django
  vulnerable_versions:
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - '1.1'
  - 1.2.4
  - 1.1.0
  - 1.1.2
  - 1.1.3
  - '1.2'
  package_manager: pypi
  cve:
  - CVE-2011-0696
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2011-February/054207.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2011-February/054208.html
  - http://openwall.com/lists/oss-security/2011/02/09/6
  - http://secunia.com/advisories/43230
  - http://secunia.com/advisories/43297
  - http://secunia.com/advisories/43382
  - http://secunia.com/advisories/43426
  - http://www.debian.org/security/2011/dsa-2163
  - http://www.djangoproject.com/weblog/2011/feb/08/security/
  - http://www.mandriva.com/security/advisories?name=MDVSA-2011:031
  - http://www.securityfocus.com/bid/46296
  - http://www.ubuntu.com/usn/USN-1066-1
  - http://www.vupen.com/english/advisories/2011/0372
  - http://www.vupen.com/english/advisories/2011/0388
  - http://www.vupen.com/english/advisories/2011/0429
  - http://www.vupen.com/english/advisories/2011/0439
  - http://www.vupen.com/english/advisories/2011/0441
  - https://bugzilla.redhat.com/show_bug.cgi?id=676357
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2008-09-04
  title: "[CVE-2008-3909]  Cross-Site Request Forgery (CSRF)"
  description: The administration application in Django 0.91, 0.95, and 0.96 stores
    unauthenticated HTTP POST requests and processes them after successful authentication
    occurs, which allows remote attackers to conduct cross-site request forgery (CSRF)
    attacks and delete or modify data via unspecified requests.
  affected_package: Django
  vulnerable_versions:
  - '0.91'
  - '0.95'
  - '0.96'
  package_manager: pypi
  cve:
  - CVE-2008-3909
  credit:
  - OSSIndex
  references:
  - http://osvdb.org/47906
  - http://secunia.com/advisories/31837
  - http://secunia.com/advisories/31961
  - http://www.debian.org/security/2008/dsa-1640
  - http://www.djangoproject.com/weblog/2008/sep/02/security/
  - http://www.openwall.com/lists/oss-security/2008/09/03/4
  - http://www.vupen.com/english/advisories/2008/2533
  - https://bugzilla.redhat.com/show_bug.cgi?id=460966
  - https://www.redhat.com/archives/fedora-package-announce/2008-September/msg00091.html
  - https://www.redhat.com/archives/fedora-package-announce/2008-September/msg00131.html
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2008-05-23
  title: '[CVE-2008-2302]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: Cross-site scripting (XSS) vulnerability in the login form in the administration
    application in Django 0.91 before 0.91.2, 0.95 before 0.95.3, and 0.96 before
    0.96.2 allows remote attackers to inject arbitrary web script or HTML via the
    URI of a certain previous request.
  affected_package: Django
  vulnerable_versions:
  - '0.91'
  - '0.95'
  - '0.96'
  package_manager: pypi
  cve:
  - CVE-2008-2302
  credit:
  - OSSIndex
  references:
  - http://secunia.com/advisories/30250
  - http://secunia.com/advisories/30291
  - http://securitytracker.com/id?1020028
  - http://www.djangoproject.com/weblog/2008/may/14/security/
  - http://www.securityfocus.com/bid/29209
  - http://www.vupen.com/english/advisories/2008/1618
  - http://xforce.iss.net/xforce/xfdb/42396
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2007-10-30
  title: "[CVE-2007-5712]  Resource Management Errors"
  description: The internationalization (i18n) framework in Django 0.91, 0.95, 0.95.1,
    and 0.96, and as used in other products such as PyLucid, when the USE_I18N option
    and the i18n component are enabled, allows remote attackers to cause a denial
    of service (memory consumption) via many HTTP requests with large Accept-Language
    headers.
  affected_package: Django
  vulnerable_versions:
  - '0.91'
  - '0.95'
  - 0.95.1
  - '0.96'
  package_manager: pypi
  cve:
  - CVE-2007-5712
  credit:
  - OSSIndex
  references:
  - http://secunia.com/advisories/27435
  - http://secunia.com/advisories/27597
  - http://secunia.com/advisories/31961
  - http://sourceforge.net/forum/forum.php?forum_id=749199
  - http://www.debian.org/security/2008/dsa-1640
  - http://www.djangoproject.com/weblog/2007/oct/26/security-fix
  - http://www.securityfocus.com/bid/26227
  - http://www.vupen.com/english/advisories/2007/3660
  - http://www.vupen.com/english/advisories/2007/3661
  - http://xforce.iss.net/xforce/xfdb/38143
  - https://www.redhat.com/archives/fedora-package-announce/2007-November/msg00243.html
  - https://www.redhat.com/archives/fedora-package-announce/2007-November/msg00257.html
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-02-14
  title: '[CVE-2011-0698]  Improper Limitation of a Pathname to a Restricted Directory
    ("Path Traversal")'
  description: Directory traversal vulnerability in Django 1.1.x before 1.1.4 and
    1.2.x before 1.2.5 on Windows might allow remote attackers to read or execute
    files via a / (slash) character in a key in a session cookie, related to session
    replays.
  affected_package: Django
  vulnerable_versions:
  - 1.1.3
  - '1.2'
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - '1.1'
  - 1.2.4
  - 1.1.0
  - 1.1.2
  package_manager: pypi
  cve:
  - CVE-2011-0698
  credit:
  - OSSIndex
  references:
  - http://openwall.com/lists/oss-security/2011/02/09/6
  - http://secunia.com/advisories/43230
  - http://www.djangoproject.com/weblog/2011/feb/08/security/
  - http://www.mandriva.com/security/advisories?name=MDVSA-2011:031
  - http://www.securityfocus.com/bid/46296
  - http://www.vupen.com/english/advisories/2011/0372
  - http://www.vupen.com/english/advisories/2011/0439
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-01-10
  title: "[CVE-2010-4535]  Improper Input Validation"
  description: The password reset functionality in django.contrib.auth in Django before
    1.1.3, 1.2.x before 1.2.4, and 1.3.x before 1.3 beta 1 does not validate the length
    of a string representing a base36 timestamp, which allows remote attackers to
    cause a denial of service (resource consumption) via a URL that specifies a large
    base36 integer.
  affected_package: Django
  vulnerable_versions:
  - '1.0'
  - 1.2.2
  - 1.0.1
  - 1.2.3
  - 1.0.2
  - '1.3'
  - '1.1'
  - '0.91'
  - 1.1.0
  - '0.95'
  - 1.1.2
  - 0.95.1
  - '1.2'
  - '0.96'
  - 1.2.1
  package_manager: pypi
  cve:
  - CVE-2010-4535
  credit:
  - OSSIndex
  references:
  - http://code.djangoproject.com/changeset/15032
  - http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053041.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053072.html
  - http://secunia.com/advisories/42715
  - http://secunia.com/advisories/42827
  - http://secunia.com/advisories/42913
  - http://www.djangoproject.com/weblog/2010/dec/22/security/
  - http://www.openwall.com/lists/oss-security/2010/12/23/4
  - http://www.openwall.com/lists/oss-security/2011/01/03/5
  - http://www.securityfocus.com/bid/45563
  - http://www.ubuntu.com/usn/USN-1040-1
  - http://www.vupen.com/english/advisories/2011/0048
  - http://www.vupen.com/english/advisories/2011/0098
  - https://bugzilla.redhat.com/show_bug.cgi?id=665373
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2011-01-10
  title: "[CVE-2010-4534]  Permissions, Privileges, and Access Controls"
  description: The administrative interface in django.contrib.admin in Django before
    1.1.3, 1.2.x before 1.2.4, and 1.3.x before 1.3 beta 1 does not properly restrict
    use of the query string to perform certain object filtering, which allows remote
    authenticated users to obtain sensitive information via a series of requests containing
    regular expressions, as demonstrated by a created_by__password__regex parameter.
  affected_package: Django
  vulnerable_versions:
  - '0.96'
  - 1.2.1
  - '0.91'
  - '1.0'
  - 1.2.2
  - '0.95'
  - 1.0.1
  - 1.2.3
  - 0.95.1
  - 1.0.2
  - '1.3'
  - '1.1'
  - 1.1.0
  - 1.1.2
  - '1.2'
  package_manager: pypi
  cve:
  - CVE-2010-4534
  credit:
  - OSSIndex
  references:
  - http://archives.neohapsis.com/archives/fulldisclosure/2010-12/0580.html
  - http://code.djangoproject.com/changeset/15031
  - http://evilpacket.net/2010/dec/22/information-leakage-django-administrative-interfac/
  - http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053041.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053072.html
  - http://ngenuity-is.com/advisories/2010/dec/22/information-leakage-in-django-administrative-inter/
  - http://secunia.com/advisories/42715
  - http://secunia.com/advisories/42827
  - http://secunia.com/advisories/42913
  - http://www.djangoproject.com/weblog/2010/dec/22/security/
  - http://www.openwall.com/lists/oss-security/2010/12/23/4
  - http://www.openwall.com/lists/oss-security/2011/01/03/5
  - http://www.securityfocus.com/archive/1/515446
  - http://www.securityfocus.com/bid/45562
  - http://www.ubuntu.com/usn/USN-1040-1
  - http://www.vupen.com/english/advisories/2011/0048
  - http://www.vupen.com/english/advisories/2011/0098
  - https://bugzilla.redhat.com/show_bug.cgi?id=665373
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2010-09-14
  title: '[CVE-2010-3082]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: Cross-site scripting (XSS) vulnerability in Django 1.2.x before 1.2.2
    allows remote attackers to inject arbitrary web script or HTML via a csrfmiddlewaretoken
    (aka csrf_token) cookie.
  affected_package: Django
  vulnerable_versions:
  - 1.2.1
  - 1.2.2
  package_manager: pypi
  cve:
  - CVE-2010-3082
  credit:
  - OSSIndex
  references:
  - http://marc.info/?l=oss-security&m=128403961700444&w=2
  - http://www.djangoproject.com/weblog/2010/sep/08/security-release/
  - http://www.securityfocus.com/bid/43116
  - http://www.ubuntu.com/usn/USN-1004-1
  - http://xforce.iss.net/xforce/xfdb/61729
  - https://bugzilla.redhat.com/show_bug.cgi?id=632239
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2009-10-13
  title: "[CVE-2009-3695] Algorithmic complexity vulnerability in the forms library
    in Django 1.0 before 1..."
  description: Algorithmic complexity vulnerability in the forms library in Django
    1.0 before 1.0.4 and 1.1 before 1.1.1 allows remote attackers to cause a denial
    of service (CPU consumption) via a crafted (1) EmailField (email address) or (2)
    URLField (URL) that triggers a large amount of backtracking in a regular expression.
  affected_package: Django
  vulnerable_versions:
  - '1.0'
  - '1.1'
  package_manager: pypi
  cve:
  - CVE-2009-3695
  credit:
  - OSSIndex
  references:
  - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457
  - http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51/
  - http://secunia.com/advisories/36948
  - http://secunia.com/advisories/36968
  - http://www.debian.org/security/2009/dsa-1905
  - http://www.djangoproject.com/weblog/2009/oct/09/security/
  - http://www.openwall.com/lists/oss-security/2009/10/13/6
  - http://www.securityfocus.com/bid/36655
  - http://www.vupen.com/english/advisories/2009/2871
  - http://xforce.iss.net/xforce/xfdb/53727
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2009-08-04
  title: '[CVE-2009-2659]  Improper Limitation of a Pathname to a Restricted Directory
    ("Path Traversal")'
  description: The Admin media handler in core/servers/basehttp.py in Django 1.0 and
    0.96 does not properly map URL requests to expected "static media files," which
    allows remote attackers to conduct directory traversal attacks and read arbitrary
    files via a crafted URL.
  affected_package: Django
  vulnerable_versions:
  - '0.96'
  - '1.0'
  package_manager: pypi
  cve:
  - CVE-2009-2659
  credit:
  - OSSIndex
  references:
  - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=539134
  - http://code.djangoproject.com/changeset/11353
  - http://secunia.com/advisories/36137
  - http://secunia.com/advisories/36153
  - http://www.djangoproject.com/weblog/2009/jul/28/security/
  - http://www.openwall.com/lists/oss-security/2009/07/29/2
  - http://www.securityfocus.com/bid/35859
  - https://www.redhat.com/archives/fedora-package-announce/2009-August/msg00055.html
  - https://www.redhat.com/archives/fedora-package-announce/2009-August/msg00069.html
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2007-11-05
  title: "[CVE-2007-5828]  Cross-Site Request Forgery (CSRF)"
  description: "** DISPUTED **  Cross-site request forgery (CSRF) vulnerability in
    the admin panel in Django 0.96 allows remote attackers to change passwords of
    arbitrary users via a request to admin/auth/user/1/password/.  NOTE: this issue
    has been disputed by Debian, since product documentation includes a recommendation
    for a CSRF protection module that is included with the product.  However, CVE
    considers this an issue because the default configuration does not use this module."
  affected_package: Django
  vulnerable_versions:
  - '0.96'
  package_manager: pypi
  cve:
  - CVE-2007-5828
  credit:
  - OSSIndex
  references:
  - http://osvdb.org/45285
  - http://securityreason.com/securityalert/3338
  - http://www.securityfocus.com/archive/1/archive/1/482983/100/0/threaded
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2007-01-23
  title: "[CVE-2007-0405] The LazyUser class in the AuthenticationMiddleware for Django
    0.95 does not prop..."
  description: The LazyUser class in the AuthenticationMiddleware for Django 0.95
    does not properly cache the user name across requests, which allows remote authenticated
    users to gain the privileges of a different user.
  affected_package: Django
  vulnerable_versions:
  - '0.95'
  package_manager: pypi
  cve:
  - CVE-2007-0405
  credit:
  - OSSIndex
  references:
  - http://code.djangoproject.com/changeset/3754
  - http://secunia.com/advisories/23826
  - http://www.securityfocus.com/bid/22138
  - http://xforce.iss.net/xforce/xfdb/31628
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: ossindex:pypi:Django:2007-01-23
  title: "[CVE-2007-0404] bin/compile-messages.py in Django 0.95 does not quote argument
    strings before in..."
  description: bin/compile-messages.py in Django 0.95 does not quote argument strings
    before invoking the msgfmt program through the os.system function, which allows
    attackers to execute arbitrary commands via shell metacharacters in a (1) .po
    or (2) .mo file.
  affected_package: Django
  vulnerable_versions:
  - '0.95'
  package_manager: pypi
  cve:
  - CVE-2007-0404
  credit:
  - OSSIndex
  references:
  - http://code.djangoproject.com/changeset/3592
  - http://secunia.com/advisories/23826
  - http://www.securityfocus.com/bid/22134
  - http://xforce.iss.net/xforce/xfdb/31627
  source_url: https://ossindex.net/resource/package/8400868970/vulnerabilities
- id: victims:pypi:Django:date
  title: 'Django: unexpected code execution using reverse()'
  description: 'A flaw was found in the way Django''s reverse() URL resolver function
    constructed certain URLs. A remote attacker able to request a specially crafted
    view from a Django application could use this flaw to import and execute arbitrary
    Python modules on the system under the privileges of the user running the application.

'
  affected_package: Django
  vulnerable_versions:
  - "<=1.7b1"
  - '1.7'
  - "<=1.6.2"
  - '1.6'
  - "<=1.5.5"
  - '1.5'
  - "<=1.4.10"
  - '1.4'
  patched_versions:
  - ">=1.7b2"
  - '1.7'
  - ">=1.6.3"
  - '1.6'
  - ">=1.5.6"
  - '1.5'
  - ">=1.4.11"
  - '1.4'
  severity: medium
  package_manager: pypi
  cve:
  - 2014-0472
  credit:
  - Victims CVE Database
  references:
  - https://www.djangoproject.com/weblog/2014/apr/21/security/
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-0472
  - https://rhn.redhat.com/errata/RHSA-2014-0456.html
  - https://www.debian.org/security/2014/dsa-2934
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2014/0472.yaml
- id: victims:pypi:Django:date
  title: 'Django: MySQL typecasting'
  description: 'It was discovered that certain Django model field classes did not
    properly perform type conversion on their arguments. A remote attacker could use
    this flaw to submit a specially crafted SQL query that, when processed by a Django
    application using a MySQL database, could have various application-specific impacts
    on the MySQL database.

'
  affected_package: Django
  vulnerable_versions:
  - "<=1.7b1"
  - '1.7'
  - "<=1.6.2"
  - '1.6'
  - "<=1.5.5"
  - '1.5'
  - "<=1.4.10"
  - '1.4'
  patched_versions:
  - ">=1.7b2"
  - '1.7'
  - ">=1.6.3"
  - '1.6'
  - ">=1.5.6"
  - '1.5'
  - ">=1.4.11"
  - '1.4'
  severity: medium
  package_manager: pypi
  cve:
  - 2014-0474
  credit:
  - Victims CVE Database
  references:
  - https://www.djangoproject.com/weblog/2014/apr/21/security/
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-0474
  - https://rhn.redhat.com/errata/RHSA-2014-0456.html
  - https://www.debian.org/security/2014/dsa-2934
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2014/0474.yaml
- id: victims:pypi:Django:date
  title: 'Django: caching of anonymous pages could reveal CSRF token'
  description: 'It was found that Django''s caching framework reused Cross-Site Request
    Forgery (CSRF) nonces for all requests from unauthenticated clients. A remote
    attacker could use this flaw to acquire the CSRF token of a different user and
    bypass intended CSRF protections in a Django application.

'
  affected_package: Django
  vulnerable_versions:
  - "<=1.7b1"
  - '1.7'
  - "<=1.6.2"
  - '1.6'
  - "<=1.5.5"
  - '1.5'
  - "<=1.4.10"
  - '1.4'
  patched_versions:
  - ">=1.7b2"
  - '1.7'
  - ">=1.6.3"
  - '1.6'
  - ">=1.5.6"
  - '1.5'
  - ">=1.4.11"
  - '1.4'
  severity: medium
  package_manager: pypi
  cve:
  - 2014-0473
  credit:
  - Victims CVE Database
  references:
  - https://www.djangoproject.com/weblog/2014/apr/21/security/
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-0473
  - https://rhn.redhat.com/errata/RHSA-2014-0456.html
  - https://www.debian.org/security/2014/dsa-2934
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2014/0473.yaml
