---
- id: snykio:pypi:pyconau-funtimes:72536
  title: Malicious Package
  description: |+
    12 Python libraries were identified as malicious packages.
    `pyconau-funtimes` opened a reverse shell through a proxy service, so it
    was not possible to determine the other end of the connection.

    On October 13th, 2018 all of these packages have been removed from Pypi.

  affected_package: pyconau-funtimes
  vulnerable_versions:
  - ">= 0"
  severity: high
  package_manager: pypi
  cwe:
  - CWE-506
  disclosed_date: 2018-10-13
  created_date: 2018-10-28
  last_modified_date: 2018-10-28
  credit:
  - Bertus
  references:
  - https://medium.com/@bertusk/detecting-cyber-attacks-in-the-python-package-index-pypi-61ab2b585c67
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PYCONAUFUNTIMES-72536
