---
- id: snykio:pypi:pykerberos:2015-05-18
  title: Man-in-the-Middle (MitM)
  description: |
    [`pykerberos`][1] is a High-level interface to Kerberos.

    Affected versions of this package are vulnerable to a Man-in-the-Middle
    (MitM) attacks. The python-kerberos `checkPassword()` function does not
    verify that the KDC that it is authenticating with is the one that it
    intended to communicate with. This could allow a man-in-the-middle
    attacker to spoof a KDC when an application using python-kerberos
    attempts to verify a password via the `checkPassword()` function.



    [1]: https://pypi.python.org/pypi/pykerberos
    \n[`pykerberos`][1] is a High-level interface to Kerberos.

    Affected versions of this package are vulnerable to a Man-in-the-Middle
    (MitM) attacks. The python-kerberos `checkPassword()` function does not
    verify that the KDC that it is authenticating with is the one that it
    intended to communicate with. This could allow a man-in-the-middle
    attacker to spoof a KDC when an application using python-kerberos
    attempts to verify a password via the `checkPassword()` function.



    [1]: https://pypi.python.org/pypi/pykerberos
    \n[`pykerberos`][1] is a High-level interface to Kerberos.

    Affected versions of this package are vulnerable to a Man-in-the-Middle
    (MitM) attacks. The python-kerberos `checkPassword()` function does not
    verify that the KDC that it is authenticating with is the one that it
    intended to communicate with. This could allow a man-in-the-middle
    attacker to spoof a KDC when an application using python-kerberos
    attempts to verify a password via the `checkPassword()` function.



    [1]: https://pypi.python.org/pypi/pykerberos
  affected_package: pykerberos
  vulnerable_versions:
  - "< 1.1.6"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2015-3206
  cwe:
  - CWE-300
  credit:
  - Unknown
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2015-3206
  - https://github.com/02strich/pykerberos/commit/02d13860b25fab58e739f0e000bed0067b7c6f9c
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PYKERBEROS-40322
